version: 2

build-steps:
  - name: nodejs
    commands:
      - npm ci
      - npm run production
  - name: composer
    commands:
      - composer install --optimize-autoloader --no-dev
      - php artisan key:generate --force -n

template-files:
  - type: laravel-env-completion
    path: .env
    source-file: .env.example
  - type: htaccess-completion
    path: .htaccess

deploy-step:
  deployment-folder: "./"
  bootstrap:
    excludes:
      - tests
      - node_modules
      - DOCKER_ENV
      - docker_tag
      - output.log
    remote-commands:
      post-deployment:
        - find $(pwd) -type f -not -path \"$(pwd)/logs/*\" -exec chmod 664 {} \\;
        - find $(pwd) -type d -not -name \"logs\" -exec chmod 775 {} \\;
        - chmod -R o+w storage bootstrap/cache
        - php artisan migrate --force
        - php artisan optimize:clear
        - php artisan migrate --force -n
        - php artisan storage:link
        - php artisan optimize
        - php artisan up
  recurring:
    excludes:
      - tests
      - node_modules
      - DOCKER_ENV
      - docker_tag
      - output.log
      - storage
    remote-commands:
      pre-deployment:
        - php artisan down
      post-deployment:
        - find $(pwd) -type f -not -path "$(pwd)/logs/*" -exec chmod 664 {} \;
        - find $(pwd) -type d -not -name "logs" -exec chmod 775 {} \;
        - chmod -R o+w storage bootstrap/cache
        - php artisan migrate --force
        - php artisan optimize:clear
        - php artisan migrate --force -n
        - php artisan storage:link
        - php artisan optimize
        - php artisan up

required-features:
  - PHP
  - DB
  - MAIL
